### PR TITLE
Add invite and kick capability

### PR DESCRIPTION
**Pull request by nuxeh**
Now if a user for example posts `/invite url-bot-rs` in a channel, url-bot will join that channel. This is enabled with the feature `invite`.

Additionally, enabling the `autosave` feature will result in the channel being added to the list of channels in the configuration, which the bot will join on startup. The same is true for `/kick`, which will remove the channel from the list in the configuration.

### CODE REVIEW

**Comment by polyzen** [comment]
`autosave` causes some settings to be overwritten, eg. `url_limit` and `ping_timeout`.

**Comment by nuxeh** [comment]
Interesting, @polyzen. It should take the active state, which was previously deserialised from the config, modify the channel list, and then just serialise it back again, so I had assumed that it would be fine. I'll have a look.

**Comment by nuxeh** [comment]
@polyzen, was your `url_limit` (before inviting url-bot to a channel) under `[features]`, as was the case in older versions of the configuration, by any chance?

If so, since it's now under `[parameters]`, it will write out the default value under that section, rather than in `[features]`, and will most likely be using the default value at run time, too. I've also observed this since i was using a legacy configuration originally, too.

I made a test configuration with non-default values for a number of things, including the ones you mentioned, and the only diff i get between them is the channel list, so it seems ok to me.

**Comment by polyzen** [comment]
Actually it had fixed a few things for me as well. Testing it now, everything seems to work fine..

**Comment by nuxeh** [comment]
Now rebased and merged.

**Pull request closed without merging**
