### PR TITLE
Get image metadata

### PR DESCRIPTION
**Pull request by nuxeh**

### CODE REVIEW

**Comment by nuxeh** [comment]
Can come up with some odd results on giphy...

```
<dabukalam> https://media.giphy.com/media/3Z0XdseX163wQ/giphy.gif
<url-bot-rs> ⤷ image/jpeg 19303×24581
```

**Comment by nuxeh** [comment]
`immeta` may be broken for gifs...

Also, should definitely attempt to extract metadata after failing to parse titles/HTML. Some sites, e.g. giphy, seem to serve up HTML, complete with title and everything, where the path points to a `.gif`. HTML title should be preferred anyway.

**Comment by nuxeh** [comment]
It looks like this is caused by the file download limit...

```
<edcragg> https://media.giphy.com/media/3Z0XdseX163wQ/giphy.gif
<url-bot-rs> ⤷ image/gif 374×180 → Mon Oct  8 14:23:15 2018 dabukalam (#url-bot-rs)
```

Which is a bit awkward. It seems gif *may* have the metadata at the end of the file.

**Comment by panicbit** [comment]
We can probably raise or lower the limit based on the content type.

**Comment by nuxeh** [comment]
Have been thinking it could be useful to query the `Content-Type` headers, which i presume are available with `reqwest`, which could allow for fairly robust and early detection of the file type. Prior to `reqwest` i was playing with using curl to only fetch the response headers first, and then fetching the content later in a separate request depending on those.

**Comment by nuxeh** [comment]
This changes the download limit based on MIME type, and also introduces a catch-all response that gives MIME string and file size.

It's spectacularly ugly at the moment, mostly because of the MIME type matching, and the handling of the None case. I'll probably refactor it at some point.

**Pull request merged**
