### PR TITLE
Fix #46 Incorrect image metadata

### LINKED ISSUE #46: Incorrect image metadata
```
[18:56:02] <sebk> https://rynx.org/sebk/_/DSC_5503.jpg
[18:56:03] -u/#rust-offtopic- ⤷ image/jpeg 6314×40159
```

Also, it appears this is not due to file truncation, this time.

### PR DESCRIPTION
**Pull request by smirnovvad**
Changed [immeta](https://github.com/netvl/immeta) crate to [image](https://github.com/PistonDevelopers/image), immeta already have an issue about wrong exif parsing - https://github.com/netvl/immeta/issues/9.

### CODE REVIEW

**Comment by nuxeh** [comment]
Hi, thanks for the patch!

I had considered using the `image` crate previously, so this is great.

However, had held off from using `image` due to the fact that we don't need full image loading capabilities, and using image comes with a number of added secondary dependencies. However it seems to only add 400KB on top of the existing 11MB binary on x86_64, so that's not too bad.

Would you consider putting formatting changes into a separate commit, and perhaps a separate branch, to be considered and reviewed separately? It could also be an idea to create this PR from its own branch in your fork too.

It's good to see a new test, but we have had discussions previously on `#url-bot-rs` about unit testing using remote resources, and the effect it has of making them potentially non-deterministic, if external resources aren't available when the tests are run. Since we have automated CI on travis, this could be misleading. We've discussed using cached web resources, e.g. #34, but until something like that is done, it could be an idea to use local images as a source for testing.

**Comment by nuxeh** [comment]
Great, thanks, would you be able to squash these two commits?

Also, `immeta` is still included:
https://github.com/nuxeh/url-bot-rs/blob/dbfa84b66dc4b1b7a6887586250bab0bfb70f12f/Cargo.toml#L21 

Any plan to update the tests to work locally? (although this could potentially be done afterwards)

**Comment by nuxeh** [comment]
@smirnovvad the simplest method would probably be to cherry-pick that single commit by its SHA (after adding the upstream repo, this one, as a new remote in your checkout, and fetching the new remote)

Otherwise, you could rebase on top of the images branch (and force push this PR branch to update it).

In the future it is a good idea to make a new branch in your repo, to then use the branch for the PR. This would allow you to work on multiple branches at the same time (and multiple PRs), and also allow you to easily rebase and update the PR in the case that master moves on before the PR/branch is merged.

**Comment by nuxeh** [comment]
If you look into `git rebase --interactive` in theory you could use that to fixup commits dbfa84b and 2b05e9b into 23dca7d, which would make the history tidier, which is nice, but not necessary. Maybe useful for the future. After updating the branch, you could again force push it to update the PR.

**Comment by nuxeh** [comment]
By the way, if you fetch this repo you should be able to find commit 4379e27c39894206f5e6384873fe072c5861cc63, which has some small updates  to the logic. I could have reviewed them on here individually, but this shows the changes i had in mind in one go:
- removing redundant `*&body`
- getting rid of explicit return statements
- combining the logic into one if/else block
- adjusting variable names so the lines fit into 80 character width

Feel free to cherry pick this commit too, or apply the changes yourself, this isn't essential though, since i can always apply the changes later.

**Comment by nuxeh** [comment]
Interesting... have you noticed it being slow with these changes?

May be worth trying the suggestion from one of those issues of not using `Image::open()`, perhaps benchmark it, and see if that speeds it up. It may compound any speed issue since here the image is opened three times, once for each format, too.

Otherwise it shouldn't be too difficult to fix immeta for JPEG. Seems this has been a loose end for a number of people previously.

**Comment by smirnovvad** [comment]
When we use `image::{ gif, png, jpeg }`, it doesn't open the full image, instead, the decoder just reads metadata of his format.

**Comment by polyzen** [comment]
```
01:33:42             dmc | https://i.imgur.com/dS0A3q4.png https://i.imgur.com/kIBS5GM.jpg https://raw.githubuserconten
                         | t.com/nuxeh/url-bot-rs/6d7be6025b044799269a069a95a1ac8217243427/test/img/test.gif
01:33:43              -- | Notice(u): ⤷ image/png 720×958
01:33:43              -- | Notice(u): ⤷ image/jpeg 1893×4028
01:33:43              -- | Notice(u): ⤷ image/gif 1920×1080
```

**Comment by nuxeh** [comment]
That seems within reasonable expectations for processing time, especially given that the networking and polling of the IRC i have a feeling can generally take a small amount of time anyway.

@smirnovvad  yes, indeed, it is ultimately going to have to at least read the metadata from each format until if finds the match, since the data comes in as an annonymous byte array, but yes, as long as it is doing that, and not buffering the whole image then it should be fine.

This PR now seems to be empty, are you still working on it?

**Comment by nuxeh** [comment]
Actually given that 1 second is the minimum resolution of time we have here, it's probably fine :)

I'm pretty happy with using `image` in general, would be good to get this in.

**Comment by nuxeh** [comment]
@smirnovvad since this PR/branch doesn't look finished as far as i can see, i've made #59, which includes all of these changes squashed into one commit, the test images, and my amendments.

**Pull request closed without merging**
